name: Demo MMDT
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  demo-mmdt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v4
      - names: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"
      - names: Install libraries
        run: pip install -r requirements.txt
      - names: Run Python file as testing
        run: python exercise1.py

